<?php

/*
 * Table Seeder
 */
	
class Wdfms_Seeder 
{
	
    /* 
     * Seed all tables.
     * Format : 'Table_name' => [ ['data_set_1'], ['data_set_2'], ... ],
     */
    public static $data = array( 
        'wdfms_forms'          => [
                                        [   's_user_id'     => '1'            ,
                                            'p_user_id'     => '1'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2019-04-22'   , 
                                            's_rollno'      => '15'           ,
                                            's_name'        => 'Varun Patel'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         , 
                                            's_img'         => 'images/avatar2.png', 
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '2'            ,
                                            'p_user_id'     => '2'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2019-06-22'   , 
                                            's_rollno'      => '16'           ,
                                            's_name'        => 'Pratap Singh' , 
                                            's_dob'         => '2010-08-02'   ,
                                            's_gender'      => 'Male'         ,
                                            's_img'         => 'images/avatar1.png',  
                                            's_address'     => 'Sagar Road'   ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => '0 +ve'        ,
                                            's_doj'         => '2020-02-11'   ,  
                                            'p_name'        => 'Vilas Roy', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Nirupama Dev' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Momen Chauhan',
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '3'            ,
                                            'p_user_id'     => '3'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2019-04-22'   , 
                                            's_rollno'      => '17'           ,
                                            's_name'        => 'Nikunj'       , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         ,
                                            's_img'         => 'images/avatar3.png',  
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '4'            ,
                                            'p_user_id'     => '4'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2019-04-22'   , 
                                            's_rollno'      => '18'           ,
                                            's_name'        => 'Mithlesh'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         ,
                                            's_img'         => 'images/avatar4.png',  
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '5'            ,
                                            'p_user_id'     => '5'            , 
                                            'class_id'      => '2'            ,
                                            'class_date'    => '2019-04-25'   , 
                                            's_rollno'      => '19'           ,
                                            's_name'        => 'Bhanu Dev'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         , 
                                            's_img'         => 'images/avatar4.png', 
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '6'            ,
                                            'p_user_id'     => '6'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2018-02-24'   , 
                                            's_rollno'      => '20'           ,
                                            's_name'        => 'Toraji Desi'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_img'         => 'images/avatar1.png', 
                                            's_gender'      => 'Male'         , 
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '7'            ,
                                            'p_user_id'     => '7'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2017-01-15'   , 
                                            's_rollno'      => '15'           ,
                                            's_name'        => 'Niranjan singh'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         ,
                                            's_img'         => 'images/avatar2.png',  
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        [   's_user_id'     => '8'            ,
                                            'p_user_id'     => '8'            , 
                                            'class_id'      => '1'            ,
                                            'class_date'    => '2015-05-02'   , 
                                            's_rollno'      => '15'           ,
                                            's_name'        => 'Rakesh'  , 
                                            's_dob'         => '2010-02-05'   ,
                                            's_gender'      => 'Male'         ,
                                            's_img'         => 'images/avatar4.png',  
                                            's_address'     => 'Swar Society' ,
                                            's_city'        => 'Ahmedabad'    ,
                                            's_state'       => 'Gujrat'       , 
                                            's_country'     => 'India'        ,
                                            's_zip'         => '380060'       ,
                                            's_phone'       => '956289754'    , 
                                            's_email'       => 'abc@test.com' ,
                                            's_bloodgrp'    => 'A +ve'        ,
                                            's_doj'         => '2020-01-11'   ,  
                                            'p_name'        => 'Prabhat Patel', 
                                            'p_gender'      => 'Male'         ,
                                            'p_relation'    => 'Father'       ,
                                            'p_address'     => 'Swar Society' ,   
                                            'p_city'        => 'Ahmedabad'    , 
                                            'p_state'       => 'Gujrat'       , 
                                            'p_country'     => 'India'        , 
                                            'p_zip'         => '380060'       , 
                                            'p_edu'         => 'Graduation'   , 
                                            'p_phone'       => '526341745'    ,
                                            'p_email'       => 'email@email.com' ,
                                            'p_profession'  => 'Advocate'     ,
                                            'p_bloodgrp'    => 'A +ve'        ,
                                            'p1_name'       => 'Mamta Desai'  ,
                                            'p1_gender'     => 'Female'       ,
                                            'p1_relation'   => 'Mother'       ,
                                            'p1_address'    => 'Swar Society' , 
                                            'p1_city'       => 'Ahmedabad'    , 
                                            'p1_state'      => 'Gujrat'       ,
                                            'p1_country'    => 'India'        , 
                                            'p1_zip'        => '380060'       , 
                                            'p1_edu'        => 'Intermediate' ,
                                            'p1_phone'      => '695847142'    ,
                                            'p1_email'      => 'mom@email.com',
                                            'p1_profession' => 'House wife'   ,
                                            'p1_bloodgrp'   => 'B +ve'        ,
                                        ],
                                        
                                    ],
                                    
        // 'Table_name'            =>  [   [ 'set-1' ], [ 'set-2' ]    ],

                            );
    
    
    /**
     * Need not to edit below this.
     * Table data feed.
     */
    public static function seed_tables() {
        global $wpdb;    

        foreach (self::$data as $key => $values) {
            // Assign table name.
            $table_name = $wpdb->prefix . $key ;
            foreach ($values as $value) {
                // Insert values.                
                $wpdb->insert($table_name, $value);
            }            
        }        
    }


}
